SHAKESPEAR_GENRES = {
    "a-midsummer-nights-dream": "Comedy",
    "alls-well-that-ends-well": "Comedy",
    "antony-and-cleopatra": "Tragedy",
    "as-you-like-it": "Comedy",
    "coriolanus": "Tragedy",
    "cymbeline": "Tragedy",
    "hamlet": "Tragedy",
    "henry-iv-part-i": "Tragedy",
    "henry-iv-part-1": "Tragedy",
    "henry-iv-part-ii": "Tragedy",
    "henry-iv-part-2": "Tragedy",
    "henry-v": "Tragedy",
    "henry-vi-part-1": "Tragedy",
    "henry-vi-part-2": "Tragedy",
    "henry-vi-part-3": "Tragedy",
    "henry-viii": "Tragedy",
    "julius-caesar": "Tragedy",
    "king-john": "Tragedy",
    "king-lear": "Tragedy",
    "loves-labors-lost": "Comedy",
    "macbeth": "Tragedy",
    "measure-for-measure": "Comedy",
    "much-ado-about-nothing": "Comedy",
    "othello": "Tragedy",
    "pericles": "Tragedy",
    "richard-ii": "Tragedy",
    "richard-iii": "Tragedy",
    "romeo-and-juliet": "Tragedy",
    "the-comedy-of-errors": "Comedy",
    "the-merchant-of-venice": "Comedy",
    "the-merry-wives-of-windsor": "Comedy",
    "the-taming-of-the-shrew": "Comedy",
    "the-tempest": "Comedy",
    "the-winters-tale": "Comedy",
    "timon-of-athens": "Tragedy",
    "titus-andronicus": "Tragedy",
    "troilus-and-cressida": "Tragedy",
    "twelfth-night": "Comedy",
    "two-gentlemen-of-verona": "Comedy",
}

SHAKESPEAR_TEI_FILES = '/home/misinagy/Projects/shakedracor/tei'
