# Local DraCor instance with ShakeDraCor + HunDraCor pre-loaded.
# Data populated 2026-02-20, API version 1.2.2.
#
# Usage:
#   docker compose -f compose.szemes.yml up
#
# The API will be available at http://localhost:8088/api/v1/
# The frontend will be available at http://localhost:8088/
name: szemes-dracor
services:
  api:
    image: ingoboerner/szemes-dracor-api:v2
    environment:
      - DRACOR_API_BASE=http://localhost:8088/api/v1
      - EXIST_PASSWORD=
    depends_on:
      - fuseki
      - metrics
  fuseki:
    image: dracor/fuseki:1.1.3
    environment:
      - ADMIN_PASSWORD=qwerty
  metrics:
    image: dracor/metrics:1.5.1
  frontend:
    image: dracor/frontend:2.5.1
    environment:
      NGINX_RESOLVER: "127.0.0.11"
      DRACOR_API_HOST: http://api:8080
      DRACOR_API_PREFIX: /exist/restxq/v1
    depends_on:
      - api
    ports:
      - 8088:80
